# Generated by Django 3.2.9 on 2022-04-03 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0003_auto_20220403_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill_type', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta Credito', 'Tarjeta Credito'), ('Tarjeta Debito', 'Tarjeta Debito'), ('Pasarela de Pago', 'Pasarela de Pago')], max_length=255, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
    ]
