# Generated by Django 3.2.9 on 2022-04-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_historicalroom_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalroom',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='historicalroom',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='historicalroom',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='historicalroom',
            name='created_at',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='historicalroom',
            name='modified_at',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='room',
            name='modified_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
    ]
