# Generated by Django 3.2.9 on 2022-04-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20220401_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalroom',
            name='price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='historicalroom',
            name='price_day',
            field=models.PositiveIntegerField(default=0, verbose_name='Price day'),
        ),
        migrations.AddField(
            model_name='room',
            name='price_day',
            field=models.PositiveIntegerField(default=0, verbose_name='Price day'),
        ),
    ]
