# Generated by Django 3.2.9 on 2022-04-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20220401_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='active',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='HistoricalRoom',
        ),
    ]
