# Generated by Django 3.2.9 on 2022-04-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20220401_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Doble', 'Doble'), ('Matrimonial', 'Matrimonial'), ('Especial', 'Especial')], max_length=40, verbose_name='Room Type'),
        ),
    ]
